uwe5622: bluetooth: Fix firmware init fail for UniSOC BT driver
source
https://github.com/afaulkner420/build-opi3-lts/blob/master/patch/kernel/archive/sunxi-5.15/0008-uwe5622-bluetooth-fix-firmware-init-fail.patch

when link policy is written it fails for some reason

< HCI Command: Write Default Link Policy Settings (0x02|0x000f) plen 2
    policy 0x0d
    Link policy: RSWITCH SNIFF PARK
> HCI Event: Command Complete (0x0e) plen 4
    Write Default Link Policy Settings (0x02|0x000f) ncmd 1
    status 0x12
    Error: Invalid HCI Command Parameters

and device stays in DOWN state
maybe because "Link policy" is not set?

$ hciconfig -a
hci0:   Type: Primary  Bus: UART
        BD Address: E8:51:77:4D:60:A3  ACL MTU: 1021:8  SCO MTU: 240:3
        DOWN
        RX bytes:539 acl:0 sco:0 events:22 errors:0
        TX bytes:351 acl:0 sco:0 commands:22 errors:0
        Features: 0xbf 0xff 0x8d 0xfe 0xdb 0x3d 0x7b 0xc7
        Packet type: DM1 DM3 DM5 DH1 DH3 DH5 HV1 HV2 HV3
        Link policy:
        Link mode: PERIPHERAL ACCEPT